### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ghost** [lukesmurray/markdown-anki-decks#1]
Hi, Fantastic project! :)
It's the best anki-markdown integration tool I've seen.
After some playing around with it, I found some things that would really improve the tool imo.
Could you consider adding any of the following features?

---

**Mathjax support:**
The exported cards right now can't show math equations like the one below correctly
\[\mathbb{E}[f(x)] = \sum_x p(x)f(x)\]

---

**Styles for the whole page:**
Could you implement a way to have styles at the top of the markdown file apply to the whole page?

For example if the top of my page begins with
<style>d {color:rgb(50, 125, 195); font-weight: bold}</style>
All text wrapped around the style throughout the whole page should have it apply
Right now I have to define a style for every single card for it to work

---

**Ability to edit questions:**
Can you think of a way of changing the question name without resetting things? Maybe have some ID that we can optionally write somewhere under a comment that it could use if it finds it.

---

**Auto add tags:**
Add a tag to the card if there exist somewhere in the answer field

---

**Question newlines:**
The way you have setup seperating the questions foces you to never have newlines in your questions. Could you think of a way of not having that limitation, for example having the question be between 2 rarely used charactes.

---

**Optional deck title:**

If a deck title is missing in the first line, could it just get it from the filename itself?

---

**Nightmode code syntax:**
Could you have it so that the code syntax is dark when in night mode in Anki?

---

**Anki Addon**

And finally maybe you could create a very simple Anki addon that can do the syncing for you so that you could do it through the application instead of a terminal.

**Comment by lukesmurray** [comment]
Thanks for the feedback. I tried to address everything here. Let me know what you think of the workarounds I proposed. I think all of this is possible except for editing questions.

- Mathjax and styles are probably possible. most likely with yaml frontmatter.
- Editing questions is more difficult. It adds a bunch of complexity to the project and this project is intentionally kept quite simple. Other tools such as [obsidian_to_anki](https://github.com/Pseudonium/Obsidian_to_Anki) support editing questions but in order to do that they need to modify your markdown files with [html comments](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Updating-existing-notes). I want to keep the markdown read only if possible.
- tags are probably possible. I assume you want something like `#tag` syntax? In that case I can try to modify [an existing extension](https://github.com/Kongaloosh/python-markdown-hashtag-extension)
- newlines are possible but I'm hesitant to change the syntax to support magic characters. You can use raw html though and make any question style you want. Anything in an h2 tag is valid.

The current release already supports this style of multiline question

```html
<h2>
<p>Line 1</p>
<p>Line 2</p>
<p>Line 3</p>
<p>Line 4</p>
</h2>

This is your answer
```

I could add the `md_in_html` extension and you could wrap markdown in an h2 tag to create your questions.
In this sense the magic character would be `<h2 markdown="1">`.

```html
<h2 markdown="1">
- this question
- is actually
- a markdown list
</h2>

This is your answer
```

- deck title could come from the file that's fine, probably without any transformations though other than removing the extension just to keep things simple
- nightmode may be possible but requires manual work (is there a [theme you would prefer](https://help.farbox.com/pygments.html) for night mode)
- we already support syncing. Just pass a third argument of `True` to mdankideck. (`mdankideck INPUT_DIR OUTPUT_DIR SYNC`) So for example `mdankideck ./markdown_dir ./anki_deck_dir True` would create your anki decks in `anki_deck_dir` then sync them to anki. Just make sure to follow the [syncing instructions](https://github.com/lukesmurray/markdown-anki-decks#syncing) in the readme.

**Comment by lukesmurray** [comment]
I pushed some changes which should address most of these issues. The only outstanding feature requests are tags and editing questions.

- [x] Mathjax works out of the box I added documentation in the readme
- [x] added support for custom css style sheets instructions in the readme
- [ ] still need to come up with a good idea for editing questions not sure what to do there
- [ ] tags extension may come at some point but need to make sure it's bullet proof
- [x] added directions for multiline questions to the readme
- [x] the deck title is optional `deck-without-title.md` will have the title `deck-without-title`
- [x] we now use monokai for night mode and default for light mode
- [x] anki syncing is already supported with anki connect
