### ISSUE TITLE
Support Latex Inline Math $$

### ISSUE THREAD

**Issue by yannickfunk** [lukesmurray/markdown-anki-decks#5]
First of all thank you for this nice tool,
Unfortunately it was not fitting for my purpose, because inline math used in the markdown file with $$ was not converted to mathjax (aka parse $$ to \( \) ). It would be very nice if this feature could be added

**Comment by lukesmurray** [comment]
Inline math is supported by markdown-anki-decks. It is documented in the readme ([see Mathjax in the readme](https://github.com/lukesmurray/markdown-anki-decks#mathjax)). You need to use `\\(` and `\\)` as your delimiters.

```
<!-- this will render inline math -->

\\(\sqrt{x}\\)
```

Anki does not use `$` out of the box because it overlaps with Anki's built-in cloze deletion syntax ([see anki documentation](https://faqs.ankiweb.net/customizing-mathjax.html)).

Let me know if the solution works for you and I'll reopen the issue. Also open to ideas for alternative, but Anki-compatible syntaxes, if you want to help improve the experience of writing math in markdown-anki-decks.

**Comment by rasmus-kirk** [comment]
It seems to have a lot of issues with stuff like `\\( x_a = y_a \\)`.
