### ISSUE TITLE
Wrongly formatted bullet list when additional text present

### ISSUE THREAD

**Issue by MatCyg** [lukesmurray/markdown-anki-decks#6]
Thank you a lot for the software you've built, it is the best markdown to Anki parser there is!

I have an issue with some of the lists I have in my answers. If the answer only contains a list, it is properly formatted. However, if there are additional sentences that are not part of the list, the list is inlined.

Here is an example markdown file:
```markdown
# Test deck

## Properly formatted note with a list
- First
- Second
- Third

## Wrongly formatted note with a list
Some text:
- First
- Second
- Third

## Another wrongly formatted note with a list
Some text:
- First
- Second
- Third

Some other text:
- First
- Second
- Third

```
<img width="489" alt="image" src="https://user-images.githubusercontent.com/6665661/158381012-6895c7a1-9612-442f-8c01-1a43dd68838a.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/6665661/158381035-b5689514-a917-4924-a8c8-15642760cd6c.png">

**Comment by lukesmurray** [comment]
@MatCyg  glad you enjoy the software! Thank you for reporting the issue. I will try to resolve it as soon as I have time but if you want to have a go and try to solve it yourself here are some tips.

This library does not actually handle the markdown parsing. It relies on [python-markdown](https://github.com/Python-Markdown/markdown/) with the following extensions enabled.

https://github.com/lukesmurray/markdown-anki-decks/blob/de6556d7ecd2d39335607c05171f8a9c39c8f422/markdown_anki_decks/cli.py#L100-L103

This is most likely an issue with python-markdown.
However it could also be an issue with the way you are writing your markdown. You may need to add a space between your text and the list.
If this helps solve your issue please let me know so we don't duplicate work.
Otherwise I'll get to it sometime in the next couple of days.

```
## Wrongly formatted note with a list
Some text:

- First
- Second
- Third

## Another wrongly formatted note with a list
Some text:

- First
- Second
- Third

Some other text:

- First
- Second
- Third
```

**Comment by MatCyg** [comment]
I played around a bit with `python-markdown`, and it is a Markdown processor and not CommonMark. 

The issue with the list is one of the quirky differences between them. I don't think there's anything we can do about that. Adding a new line solves the issue which is good enough for me. 

Thank you for the reply. I propose to close this issue.

**Comment by lukesmurray** [comment]
@MatCyg thanks for solving this! If you have any ideas for how we could improve our python-markdown integration please let me know.
